#!/usr/bin/env python3
"""
gpio-monitor is a program that will wait and display GPIO status when it change. The goal is
learning how to manipulate gpio through python3.

We will use some basic python module to have more versatility (as argparse) but we will embeded
it on sub-module so it will not interfer with basic GPIO command.
"""
from gpio_monitor.cli import config as cfg, display as dsp
from gpio_monitor.gpio import GPIOSMonitoring


def run():
    """
    Define run function that will be started
    """
    print('run gpio-monitor')
    config = cfg.Config()
    print('Configuration {}'.format(config.display()))

    channels = GPIOSMonitoring(config.config['gpio'])
    display = dsp.Display()
    display.draw()


if __name__ == '__main__':
    run()
