#!/usr/bin/env python3
"""
"""
from press_to_enlight.cli import config as cfg
from press_to_enlight.gpio import GPIO


def run():
    """
    Define run function that will be started
    """
    config = cfg.Config()
    print('Configuration {}'.format(config.display()))

    gpio = GPIO(config.config)
    gpio.start()


if __name__ == '__main__':
    run()
